version: '3.8'

services:
  app:
    build: .
    container_name: railway-api-app
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://user:password@db/railway_db
      - JWT_SECRET_KEY=your_jwt_secret_key
      - SECRET_KEY=your_flask_secret_key
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: railway-api-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=railway_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
